apiVersion: skaffold/v1
kind: Config
build:
  local:
    useBuildkit: true
    useDockerCLI: false
    push: true
  artifacts:
    - image: gcr.io/prota-jarvis/jarvis

deploy:
  helm:
    releases:
      - name: jarvis
        chartPath: ./charts/jarvis/
        imageStrategy:
          helm:
            explicitRegistry: false
        values:
          "image": gcr.io/prota-jarvis/jarvis

        setValues:
          "solr.authentication.adminPassword": "solrPassword"
          "legalFrontend.ingress.hostname": agnes.demo
