swagger: "2.0"
info:
  title: Jarvis
  description: Jarvis handles your venture's adventures...
  version: 1.0.0
host: localhost:8080
produces:
  - application/json
consumes:
  - application/json
schemes:
  - http
basePath: /v1
paths:
  /health:
    get:
      operationId: Health
      responses:
        200:
          description: Health
          
  /dictations/status:
    get:
      operationId: DictationStatus
      responses:
        200:
          description: Status response
          schema:
            $ref: "#/definitions/dictationStatus"
  /dictations/start:
    post:
      operationId: Start
      responses:
        200:
          description: Start Recording
          schema:
            $ref: "#/definitions/dictationStatus"
  /dictations/stop:
    post:
      operationId: Stop
      responses:
        200:
          description: Start Recording
          schema:
            $ref: "#/definitions/dictationStatus"
  /zoom/meetings/upcoming:
    get:
      operationId: ListUpcomingMeetings
      responses:
        200:
          description: List upcoming zoom meetings that Jarvis has been invited to
          schema:
            properties:
              meetings:
                type: array
                items:
                  $ref: "#/definitions/meeting"

  /zoom/meetings/{id}:
    get:
      operationId: GetMeeting
      parameters:
        - name: id
          type: string
          in: path
          required: true
      responses:
        200:
          description: Get a given Meeting
          schema:
            $ref: "#/definitions/meeting"
  /zoom/recordings:
    get:
      operationId: ListRecordings
      responses:
        200:
          description: List of recorded meetings
          schema:
            type: array
            items:
              $ref: "#/definitions/recording"
definitions:
  meeting:
    required:
      - id
      - name
      - start
    properties:
      id:
        type: integer
        description: ID of Meeting
      name:
        type: string
        description: Name of Meeting
      start:
        type: string
        description: Start time of meeting
  recording:
    required:
      - id
      - meeting_id
    properties:
      id:
        type: string
        description: ID of Recording
      meeting_id:
        type: string
        description: Id of Meeting that is Recorded
  dictationStatus:
    required:
      - recording
      - processing
    properties:
      recording:
        type: boolean
        description: Is Jarvis recording your room?
      processing:
        type: boolean
        description: Processing

