package connectors

type Connection struct {
	AllSkills                 string `json:"all_skills"`
	BaseUrl                   string `json:"base_url"`
	Birthday                  string `json:"birthday"`
	Company                   string `json:"company"`
	Company2                  string `json:"company_2"`
	CompanyUrl                string `json:"company_url"`
	CompanyUrl2               string `json:"company_url_2"`
	ConnectionDegree          string `json:"connection_degree"`
	ConnectionsCount          string `json:"connections_count"`
	ConnectionsUrl            string `json:"connections_url"`
	Description               string `json:"description"`
	Endorsement1              string `json:"endorsement_1"`
	Endorsement2              string `json:"endorsement_2"`
	Endorsement3              string `json:"endorsement_3"`
	Endorsement4              string `json:"endorsement_4"`
	Endorsement5              string `json:"endorsement_5"`
	Endorsement6              string `json:"endorsement_6"`
	FirstName                 string `json:"first_name"`
	FullName                  string `json:"full_name"`
	Headline                  string `json:"headline"`
	ImgUrl                    string `json:"img_url"`
	JobDateRange              string `json:"job_date_range"`
	JobDateRange2             string `json:"job_date_range_2"`
	JobDescription            string `json:"job_description"`
	JobDescription2           string `json:"job_description_2"`
	JobLocation               string `json:"job_location"`
	JobLocation2              string `json:"job_location_2"`
	JobTitle                  string `json:"job_title"`
	JobTitle2                 string `json:"job_title_2"`
	LastName                  string `json:"last_name"`
	LinkedinProfile           string `json:"linkedin_profile"`
	LinkedinSalesNavigatorUrl string `json:"linkedin_sales_navigator_url"`
	Location                  string `json:"location"`
	MutualConnectionsCount    string `json:"mutual_connections_count"`
	MutualConnectionsUrl      string `json:"mutual_connections_url"`
	ProfileId                 string `json:"profile_id"`
	SavedImg                  string `json:"saved_img"`
	School                    string `json:"school"`
	School2                   string `json:"school_2"`
	SchoolDateRange           string `json:"school_date_range"`
	SchoolDateRange2          string `json:"school_date_range_2"`
	SchoolDegree              string `json:"school_degree"`
	SchoolDegree2             string `json:"school_degree_2"`
	SchoolDegreeSpec          string `json:"school_degree_spec"`
	SchoolDegreeSpec2         string `json:"school_degree_spec_2"`
	SchoolUrl                 string `json:"school_url"`
	SchoolUrl2                string `json:"school_url_2"`
	Screenshot                string `json:"screenshot"`
	Skill1                    string `json:"skill_1"`
	Skill2                    string `json:"skill_2"`
	Skill3                    string `json:"skill_3"`
	Skill4                    string `json:"skill_4"`
	Skill5                    string `json:"skill_5"`
	Skill6                    string `json:"skill_6"`
	Subscribers               string `json:"subscribers"`
	Timestamp                 string `json:"timestamp"`
	Twitter                   string `json:"twitter"`
	Vmid                      string `json:"vmid"`
	Website                   string `json:"website"`
}
