// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetMeetingHandlerFunc turns a function with the right signature into a get meeting handler
type GetMeetingHandlerFunc func(GetMeetingParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetMeetingHandlerFunc) Handle(params GetMeetingParams) middleware.Responder {
	return fn(params)
}

// GetMeetingHandler interface for that can handle valid get meeting params
type GetMeetingHandler interface {
	Handle(GetMeetingParams) middleware.Responder
}

// NewGetMeeting creates a new http.Handler for the get meeting operation
func NewGetMeeting(ctx *middleware.Context, handler GetMeetingHandler) *GetMeeting {
	return &GetMeeting{Context: ctx, Handler: handler}
}

/*GetMeeting swagger:route GET /zoom/meetings/{id} getMeeting

GetMeeting get meeting API

*/
type GetMeeting struct {
	Context *middleware.Context
	Handler GetMeetingHandler
}

func (o *GetMeeting) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetMeetingParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
