// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// ListUpcomingMeetingsOKCode is the HTTP code returned for type ListUpcomingMeetingsOK
const ListUpcomingMeetingsOKCode int = 200

/*ListUpcomingMeetingsOK List upcoming zoom meetings that Jarvis has been invited to

swagger:response listUpcomingMeetingsOK
*/
type ListUpcomingMeetingsOK struct {

	/*
	  In: Body
	*/
	Payload *ListUpcomingMeetingsOKBody `json:"body,omitempty"`
}

// NewListUpcomingMeetingsOK creates ListUpcomingMeetingsOK with default headers values
func NewListUpcomingMeetingsOK() *ListUpcomingMeetingsOK {

	return &ListUpcomingMeetingsOK{}
}

// WithPayload adds the payload to the list upcoming meetings o k response
func (o *ListUpcomingMeetingsOK) WithPayload(payload *ListUpcomingMeetingsOKBody) *ListUpcomingMeetingsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list upcoming meetings o k response
func (o *ListUpcomingMeetingsOK) SetPayload(payload *ListUpcomingMeetingsOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListUpcomingMeetingsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
