// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// ListRecordingsHandlerFunc turns a function with the right signature into a list recordings handler
type ListRecordingsHandlerFunc func(ListRecordingsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn ListRecordingsHandlerFunc) Handle(params ListRecordingsParams) middleware.Responder {
	return fn(params)
}

// ListRecordingsHandler interface for that can handle valid list recordings params
type ListRecordingsHandler interface {
	Handle(ListRecordingsParams) middleware.Responder
}

// NewListRecordings creates a new http.Handler for the list recordings operation
func NewListRecordings(ctx *middleware.Context, handler ListRecordingsHandler) *ListRecordings {
	return &ListRecordings{Context: ctx, Handler: handler}
}

/*ListRecordings swagger:route GET /zoom/recordings listRecordings

ListRecordings list recordings API

*/
type ListRecordings struct {
	Context *middleware.Context
	Handler ListRecordingsHandler
}

func (o *ListRecordings) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewListRecordingsParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
