// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/prota-studios/javis/models"
)

// ListRecordingsOKCode is the HTTP code returned for type ListRecordingsOK
const ListRecordingsOKCode int = 200

/*ListRecordingsOK List of recorded meetings

swagger:response listRecordingsOK
*/
type ListRecordingsOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Recording `json:"body,omitempty"`
}

// NewListRecordingsOK creates ListRecordingsOK with default headers values
func NewListRecordingsOK() *ListRecordingsOK {

	return &ListRecordingsOK{}
}

// WithPayload adds the payload to the list recordings o k response
func (o *ListRecordingsOK) WithPayload(payload []*models.Recording) *ListRecordingsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list recordings o k response
func (o *ListRecordingsOK) SetPayload(payload []*models.Recording) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListRecordingsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.Recording, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
