// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Jarvis handles your venture's adventures...",
    "title": "Jarvis",
    "version": "1.0.0"
  },
  "host": "localhost:8080",
  "basePath": "/v1",
  "paths": {
    "/dictations/start": {
      "post": {
        "operationId": "Start",
        "responses": {
          "200": {
            "description": "Start Recording",
            "schema": {
              "$ref": "#/definitions/dictationStatus"
            }
          }
        }
      }
    },
    "/dictations/status": {
      "get": {
        "operationId": "DictationStatus",
        "responses": {
          "200": {
            "description": "Status response",
            "schema": {
              "$ref": "#/definitions/dictationStatus"
            }
          }
        }
      }
    },
    "/dictations/stop": {
      "post": {
        "operationId": "Stop",
        "responses": {
          "200": {
            "description": "Start Recording",
            "schema": {
              "$ref": "#/definitions/dictationStatus"
            }
          }
        }
      }
    },
    "/health": {
      "get": {
        "operationId": "Health",
        "responses": {
          "200": {
            "description": "Health"
          }
        }
      }
    },
    "/zoom/meetings/upcoming": {
      "get": {
        "operationId": "ListUpcomingMeetings",
        "responses": {
          "200": {
            "description": "List upcoming zoom meetings that Jarvis has been invited to",
            "schema": {
              "properties": {
                "meetings": {
                  "type": "array",
                  "items": {
                    "$ref": "#/definitions/meeting"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/zoom/meetings/{id}": {
      "get": {
        "operationId": "GetMeeting",
        "parameters": [
          {
            "type": "string",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Get a given Meeting",
            "schema": {
              "$ref": "#/definitions/meeting"
            }
          }
        }
      }
    },
    "/zoom/recordings": {
      "get": {
        "operationId": "ListRecordings",
        "responses": {
          "200": {
            "description": "List of recorded meetings",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/recording"
              }
            }
          }
        }
      }
    }
  },
  "definitions": {
    "dictationStatus": {
      "required": [
        "recording",
        "processing"
      ],
      "properties": {
        "processing": {
          "description": "Processing",
          "type": "boolean"
        },
        "recording": {
          "description": "Is Jarvis recording your room?",
          "type": "boolean"
        }
      }
    },
    "meeting": {
      "required": [
        "id",
        "name",
        "start"
      ],
      "properties": {
        "id": {
          "description": "ID of Meeting",
          "type": "integer"
        },
        "name": {
          "description": "Name of Meeting",
          "type": "string"
        },
        "start": {
          "description": "Start time of meeting",
          "type": "string"
        }
      }
    },
    "recording": {
      "required": [
        "id",
        "meeting_id"
      ],
      "properties": {
        "id": {
          "description": "ID of Recording",
          "type": "string"
        },
        "meeting_id": {
          "description": "Id of Meeting that is Recorded",
          "type": "string"
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Jarvis handles your venture's adventures...",
    "title": "Jarvis",
    "version": "1.0.0"
  },
  "host": "localhost:8080",
  "basePath": "/v1",
  "paths": {
    "/dictations/start": {
      "post": {
        "operationId": "Start",
        "responses": {
          "200": {
            "description": "Start Recording",
            "schema": {
              "$ref": "#/definitions/dictationStatus"
            }
          }
        }
      }
    },
    "/dictations/status": {
      "get": {
        "operationId": "DictationStatus",
        "responses": {
          "200": {
            "description": "Status response",
            "schema": {
              "$ref": "#/definitions/dictationStatus"
            }
          }
        }
      }
    },
    "/dictations/stop": {
      "post": {
        "operationId": "Stop",
        "responses": {
          "200": {
            "description": "Start Recording",
            "schema": {
              "$ref": "#/definitions/dictationStatus"
            }
          }
        }
      }
    },
    "/health": {
      "get": {
        "operationId": "Health",
        "responses": {
          "200": {
            "description": "Health"
          }
        }
      }
    },
    "/zoom/meetings/upcoming": {
      "get": {
        "operationId": "ListUpcomingMeetings",
        "responses": {
          "200": {
            "description": "List upcoming zoom meetings that Jarvis has been invited to",
            "schema": {
              "properties": {
                "meetings": {
                  "type": "array",
                  "items": {
                    "$ref": "#/definitions/meeting"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/zoom/meetings/{id}": {
      "get": {
        "operationId": "GetMeeting",
        "parameters": [
          {
            "type": "string",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Get a given Meeting",
            "schema": {
              "$ref": "#/definitions/meeting"
            }
          }
        }
      }
    },
    "/zoom/recordings": {
      "get": {
        "operationId": "ListRecordings",
        "responses": {
          "200": {
            "description": "List of recorded meetings",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/recording"
              }
            }
          }
        }
      }
    }
  },
  "definitions": {
    "dictationStatus": {
      "required": [
        "recording",
        "processing"
      ],
      "properties": {
        "processing": {
          "description": "Processing",
          "type": "boolean"
        },
        "recording": {
          "description": "Is Jarvis recording your room?",
          "type": "boolean"
        }
      }
    },
    "meeting": {
      "required": [
        "id",
        "name",
        "start"
      ],
      "properties": {
        "id": {
          "description": "ID of Meeting",
          "type": "integer"
        },
        "name": {
          "description": "Name of Meeting",
          "type": "string"
        },
        "start": {
          "description": "Start time of meeting",
          "type": "string"
        }
      }
    },
    "recording": {
      "required": [
        "id",
        "meeting_id"
      ],
      "properties": {
        "id": {
          "description": "ID of Recording",
          "type": "string"
        },
        "meeting_id": {
          "description": "Id of Meeting that is Recorded",
          "type": "string"
        }
      }
    }
  }
}`))
}
