// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Meeting meeting
//
// swagger:model meeting
type Meeting struct {

	// ID of Meeting
	ID int64 `json:"id,omitempty"`

	// Name of Meeting
	Name string `json:"name,omitempty"`

	// Start time of meeting
	Start string `json:"start,omitempty"`
}

// Validate validates this meeting
func (m *Meeting) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Meeting) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Meeting) UnmarshalBinary(b []byte) error {
	var res Meeting
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
