// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Recording recording
//
// swagger:model recording
type Recording struct {

	// ID of Recording
	// Required: true
	ID *string `json:"id"`

	// Id of Meeting that is Recorded
	// Required: true
	MeetingID *string `json:"meeting_id"`
}

// Validate validates this recording
func (m *Recording) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMeetingID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Recording) validateID(formats strfmt.Registry) error {

	if err := validate.Required("id", "body", m.ID); err != nil {
		return err
	}

	return nil
}

func (m *Recording) validateMeetingID(formats strfmt.Registry) error {

	if err := validate.Required("meeting_id", "body", m.MeetingID); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Recording) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Recording) UnmarshalBinary(b []byte) error {
	var res Recording
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
